/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuningsRouteImport } from './routes/tunings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgressionsRouteImport } from './routes/progressions'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChordsRouteImport } from './routes/chords'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TuningIdRouteImport } from './routes/tuning.$id'
import { Route as ChordSlugRouteImport } from './routes/chord.$slug'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const TuningsRoute = TuningsRouteImport.update({
  id: '/tunings',
  path: '/tunings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionsRoute = ProgressionsRouteImport.update({
  id: '/progressions',
  path: '/progressions',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsRoute = ChordsRouteImport.update({
  id: '/chords',
  path: '/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningIdRoute = TuningIdRouteImport.update({
  id: '/tuning/$id',
  path: '/tuning/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordSlugRoute = ChordSlugRouteImport.update({
  id: '/chord/$slug',
  path: '/chord/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progressions': typeof ProgressionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunings': typeof TuningsRoute
  '/chord/$slug': typeof ChordSlugRoute
  '/tuning/$id': typeof TuningIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progressions': typeof ProgressionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunings': typeof TuningsRoute
  '/chord/$slug': typeof ChordSlugRoute
  '/tuning/$id': typeof TuningIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chords': typeof ChordsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/progressions': typeof ProgressionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tunings': typeof TuningsRoute
  '/chord/$slug': typeof ChordSlugRoute
  '/tuning/$id': typeof TuningIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chords'
    | '/login'
    | '/pricing'
    | '/progressions'
    | '/sitemap.xml'
    | '/tunings'
    | '/chord/$slug'
    | '/tuning/$id'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chords'
    | '/login'
    | '/pricing'
    | '/progressions'
    | '/sitemap.xml'
    | '/tunings'
    | '/chord/$slug'
    | '/tuning/$id'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/chords'
    | '/login'
    | '/pricing'
    | '/progressions'
    | '/sitemap.xml'
    | '/tunings'
    | '/chord/$slug'
    | '/tuning/$id'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChordsRoute: typeof ChordsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProgressionsRoute: typeof ProgressionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TuningsRoute: typeof TuningsRoute
  ChordSlugRoute: typeof ChordSlugRoute
  TuningIdRoute: typeof TuningIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunings': {
      id: '/tunings'
      path: '/tunings'
      fullPath: '/tunings'
      preLoaderRoute: typeof TuningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressions': {
      id: '/progressions'
      path: '/progressions'
      fullPath: '/progressions'
      preLoaderRoute: typeof ProgressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords': {
      id: '/chords'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning/$id': {
      id: '/tuning/$id'
      path: '/tuning/$id'
      fullPath: '/tuning/$id'
      preLoaderRoute: typeof TuningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chord/$slug': {
      id: '/chord/$slug'
      path: '/chord/$slug'
      fullPath: '/chord/$slug'
      preLoaderRoute: typeof ChordSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChordsRoute: ChordsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProgressionsRoute: ProgressionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TuningsRoute: TuningsRoute,
  ChordSlugRoute: ChordSlugRoute,
  TuningIdRoute: TuningIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
